# Generated by Django 6.0.5 on 2026-05-10 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_jobapplication_applied_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='extracted_skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
